---
- hosts: localhost

  tasks:
    - name: create docker image
      command: docker build -t word:latest .
      args:
        chdir: /opt/docker
    

    - name: docker image name change
      command: docker  tag word:latest  preethivi/word:latest
      args:
        chdir: /opt/docker
      

    - name: push the docker image to docker
      command: docker push preethivi/word
      args:
        chdir: /opt/docker
     
