name: React App Deployment

on: 
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to ubuntu-latest Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to Ubuntu server
        env: 
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key" build/ ${USER_NAME}@${HOST_NAME}:/var/www/html/
